"""Turn a chosen configuration into things you can actually run."""

from __future__ import annotations

import os
import shlex

from .probe import format_cpulist


def launch_script(cfg, binary, cpus=None, extra_comment="") -> str:
    args = cfg.argv(binary)[1:]           # drop the binary itself
    lines = ["#!/usr/bin/env bash",
             "# Generated by will-it-run-local.",
             "# Re-run `wirl tune` after any hardware or llama.cpp change."]
    if extra_comment:
        lines += ["#", *[f"# {l}" for l in extra_comment.splitlines()]]
    lines += ["set -euo pipefail", ""]
    if cfg.gpu_uuid:
        lines.append("# Pin the card that was measured, even if GPU indices change.")
        lines.append(f"export CUDA_VISIBLE_DEVICES={shlex.quote(cfg.gpu_uuid)}")

    pin = ""
    if cpus:
        lines.append("# Use one allowed CPU per physical core. On the reference")
        lines.append("# machine extra threads added contention without bandwidth.")
        pin = f"taskset -c {format_cpulist(cpus)} "
    lines.append(f'exec {pin}{shlex.quote(binary)} \\')
    body = []
    i = 0
    while i < len(args):
        a = args[i]
        if a.startswith("--") and i + 1 < len(args) and not args[i + 1].startswith("--"):
            body.append(f"  {a} {shlex.quote(args[i + 1])}")
            i += 2
        else:
            body.append(f"  {a}")
            i += 1
    lines.append(" \\\n".join(body))
    return "\n".join(lines) + "\n"


def systemd_unit(script_path, description, notes="", user_unit=True) -> str:
    note_lines = "\n".join(f"# {l}" for l in notes.splitlines() if l.strip())
    return f"""[Unit]
Description={description}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
{note_lines}
ExecStart={script_path}

Restart=on-failure
RestartSec=15

# A cold page cache can turn a 15 second load into several minutes.
TimeoutStartSec=900
TimeoutStopSec=120

# Stay responsive without starving the desktop, and do not be the first
# thing the OOM killer reaches for after loading 150 GB of weights.
Nice=-5
OOMScoreAdjust=-500

[Install]
WantedBy={'default.target' if user_unit else 'multi-user.target'}
"""


def write(path, content, mode=0o644):
    d = os.path.dirname(os.path.abspath(path))
    if d:
        os.makedirs(d, exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    os.chmod(path, mode)
    return path
