"""GGML tensor type table.

block size and bytes-per-block for every ggml type. These are ground truth:
generated by linking libggml-base.a and calling ggml_blck_size()/ggml_type_size()
for each value of enum ggml_type, rather than being copied from documentation.

Regenerate with tools/dump_ggml_types.c if llama.cpp adds types.
"""

# type_id -> (name, block_size, bytes_per_block)
GGML_TYPES = {
    0:  ("f32",     1,   4),
    1:  ("f16",     1,   2),
    2:  ("q4_0",    32,  18),
    3:  ("q4_1",    32,  20),
    6:  ("q5_0",    32,  22),
    7:  ("q5_1",    32,  24),
    8:  ("q8_0",    32,  34),
    9:  ("q8_1",    32,  36),
    10: ("q2_K",    256, 84),
    11: ("q3_K",    256, 110),
    12: ("q4_K",    256, 144),
    13: ("q5_K",    256, 176),
    14: ("q6_K",    256, 210),
    15: ("q8_K",    256, 292),
    16: ("iq2_xxs", 256, 66),
    17: ("iq2_xs",  256, 74),
    18: ("iq3_xxs", 256, 98),
    19: ("iq1_s",   256, 50),
    20: ("iq4_nl",  32,  18),
    21: ("iq3_s",   256, 110),
    22: ("iq2_s",   256, 82),
    23: ("iq4_xs",  256, 136),
    24: ("i8",      1,   1),
    25: ("i16",     1,   2),
    26: ("i32",     1,   4),
    27: ("i64",     1,   8),
    28: ("f64",     1,   8),
    29: ("iq1_m",   256, 56),
    30: ("bf16",    1,   2),
    34: ("tq1_0",   256, 54),
    35: ("tq2_0",   256, 66),
    39: ("mxfp4",   32,  17),
    40: ("nvfp4",   64,  36),
    41: ("q1_0",    128, 18),
    42: ("q2_0",    64,  18),
}

# Types 4, 5, 31-33, 36-38 are removed/deprecated in current llama.cpp and are
# deliberately absent: a file containing them will not load, so we should not
# silently price it.


def type_name(type_id: int) -> str:
    return GGML_TYPES.get(type_id, (f"unknown({type_id})", 0, 0))[0]


def tensor_nbytes(type_id: int, dims) -> int:
    """Exact on-disk size of a tensor, matching ggml_nbytes().

    ggml quantises along the first (fastest-varying) dimension only, so the
    row length must be a whole number of blocks and the remaining dimensions
    are a plain multiplier.
    """
    if type_id not in GGML_TYPES:
        raise ValueError(f"unknown or removed ggml type id {type_id}")
    _, blck, tsize = GGML_TYPES[type_id]
    if blck == 0:
        raise ValueError(f"ggml type id {type_id} has no size")
    ne0 = dims[0]
    rest = 1
    for d in dims[1:]:
        rest *= d
    if ne0 % blck:
        # ggml pads to whole blocks; mirror that rather than under-reporting.
        nblocks = (ne0 + blck - 1) // blck
    else:
        nblocks = ne0 // blck
    return nblocks * tsize * rest


def bits_per_weight(type_id: int) -> float:
    _, blck, tsize = GGML_TYPES.get(type_id, ("?", 0, 0))
    if not blck:
        return 0.0
    return tsize * 8.0 / blck
